services:
  - type: web
    name: electiq-backend
    env: node
    rootDir: electiq/server
    buildCommand: bash ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        sync: false

  - type: static_site
    name: electiq-frontend
    rootDir: electiq/frontend
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://electiq-backend.onrender.com
      - key: VITE_GEMINI_API_KEY
        sync: false
